---
- name: "Set fallback first_contact_deploy_user to controller user"
  become: false
  ansible.builtin.command: whoami
  register: whoami
  changed_when: false
  delegate_to: localhost
  when:
    - (first_contact_deploy_user | default('')) == ''
    - ansible_user is not defined
    - ansible_ssh_user is not defined

- name: "Set first_contact_deploy_user fact"
  ansible.builtin.set_fact:
    first_contact_deploy_user: "{{ ansible_user | default(ansible_ssh_user | default(whoami.stdout)) }}"
  when:
    - (first_contact_deploy_user | default('')) == ''
    - ansible_user is defined or ansible_ssh_user is defined or (whoami is defined and whoami.stdout is defined)

- name: "Display first_contact_deploy_user"
  ansible.builtin.debug:
    msg: "first_contact_deploy_user: {{ first_contact_deploy_user }}"
  when: first_contact_deploy_user is defined and not (first_contact_deploy_user | default('')) == ''
