---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${MOLECULE_IMAGE:-ubuntu2404}"
    image: "geerlingguy/docker-${MOLECULE_IMAGE:-ubuntu2404}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    published_ports:
      - "127.0.0.1:2222:22"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_connection: ssh
        ansible_host: "127.0.0.1"
        ansible_port: 2222
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ansible_remote_tmp: /tmp/.ansible/tmp
verifier:
  name: ansible
